export type Language = 'en' | 'hi' | 'es';

export const LANGUAGES = [
  { code: 'en' as const, name: 'English' },
  { code: 'hi' as const, name: 'हिन्दी (Hindi)' },
  { code: 'es' as const, name: 'Español (Spanish)' },
];

export const translations = {
  en: {
    // Common
    cancel: 'Cancel',
    save: 'Save',
    done: 'Done',
    ready: 'Ready',
    synced: 'Synced',
    close: 'Close',
    back: 'Back',
    loading: 'Loading…',

    // Tab bar
    homeTab: 'Home',
    pdfScanTab: 'PDF Scan',
    geoScanTab: 'Geo Scan',
    profileTab: 'Profile',

    // Home screen
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    whatToCapture: 'What would you like to capture today?',
    scanPdf: 'Scan PDF',
    scanPdfDesc: 'Pages → watermarked PDF',
    geoScan: 'Geo Scan',
    geoScanDesc: 'Photo + GPS coordinates',
    totalScans: 'Total scans',
    cloudSynced: 'Synced',
    thisWeek: 'This week',
    smartCrop: 'Smart Crop',
    smartCropDesc: 'Crop your geo-tagged photos with precise controls and aspect ratios',
    recentActivity: 'Recent activity',
    viewAll: 'View all',

    // PDF Scanner Screen
    pdfScannerTitle: 'PDF Scanner',
    pdfScannerSubtitle: 'Capture, watermark, and save documents with GPS data.',
    scanADoc: 'Scan a document',
    scanADocDesc: 'Place your document on a flat surface with good lighting. Each page will be watermarked with your GPS location, coordinates, and timestamp.',
    startScanning: 'Start scanning',
    locWatermark: 'Location watermark',
    locWatermarkDesc: 'GPS coordinates, place name, and accuracy on every page.',
    timestamp: 'Timestamp',
    timestampDesc: 'Exact capture time stamped on each scanned page.',
    downloadPdf: 'Download as PDF',
    downloadPdfDesc: 'Generates a real PDF file saved directly to your device.',
    alignDoc: 'Align document edges',
    pageCaptured: 'page captured',
    pagesCaptured: 'pages captured',
    reviewAndSave: 'Review & Save',
    reviewPages: 'Review Pages',
    addPage: 'Add Page',
    savePdf: 'Save PDF',
    pdfSavedTitle: 'PDF saved! ✅',
    pdfSavedBody: 'PDF with watermarks has been saved to your device.',
    sharePdf: 'Share PDF',
    scanMore: 'Scan more',
    discardPagesTitle: 'Discard pages?',
    discardPagesBody: 'You have scanned pages. Discard them?',
    discard: 'Discard',

    // Geo Camera Screen
    cameraAccessNeeded: 'Camera access needed',
    cameraAccessDesc: 'We need camera access to start the live preview right away.',
    startCamera: 'Start camera',
    allowLocationWatermark: 'Location watermark is off',
    allowLocationWatermarkDesc: 'Allow location to stamp latitude, longitude, accuracy, and capture time.',
    reviewYourShot: 'Review your shot',
    useThisShot: 'Use this shot',
    retake: 'Retake',
    crop: 'Crop',
    applyCrop: 'Apply Crop',

    // Profile Screen
    profile: 'Profile',
    manageAccount: 'Manage your account and preferences.',
    editProfile: 'Edit profile',
    yourActivity: 'Your activity',
    documents: 'Documents',
    locations: 'Locations',
    storage: 'Storage',
    settings: 'Settings',
    cloudSync: 'Cloud sync',
    privacySecurity: 'Privacy & security',
    appearance: 'Appearance',
    helpSupport: 'Help & support',
    changeLanguage: 'Language',
    signOut: 'Sign out',
    signingOut: 'Signing out…',
  },
  hi: {
    // Common
    cancel: 'रद्द करें',
    save: 'सहेजें',
    done: 'हो गया',
    ready: 'तैयार',
    synced: 'सिंक किया गया',
    close: 'बंद करें',
    back: 'पीछे',
    loading: 'लोड हो रहा है…',

    // Tab bar
    homeTab: 'होम',
    pdfScanTab: 'पीडीएफ स्कैन',
    geoScanTab: 'जियो स्कैन',
    profileTab: 'प्रोफ़ाइल',

    // Home screen
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    whatToCapture: 'आज आप क्या कैप्चर करना चाहेंगे?',
    scanPdf: 'पीडीएफ स्कैन करें',
    scanPdfDesc: 'पृष्ठ → वॉटरमार्क पीडीएफ',
    geoScan: 'जियो स्कैन',
    geoScanDesc: 'फोटो + जीपीएस निर्देशांक',
    totalScans: 'कुल स्कैन',
    cloudSynced: 'सिंक किया गया',
    thisWeek: 'इस सप्ताह',
    smartCrop: 'स्मार्ट क्रॉप',
    smartCropDesc: 'सटीक नियंत्रण और पहलू अनुपात के साथ अपनी जियो-टैग की गई तस्वीरों को क्रॉप करें',
    recentActivity: 'हाल की गतिविधि',
    viewAll: 'सभी देखें',

    // PDF Scanner Screen
    pdfScannerTitle: 'पीडीएफ स्कैनर',
    pdfScannerSubtitle: 'जीपीएस डेटा के साथ दस्तावेजों को कैप्चर, वॉटरमार्क और सहेजें।',
    scanADoc: 'दस्तावेज़ स्कैन करें',
    scanADocDesc: 'अच्छी रोशनी वाली समतल सतह पर अपना दस्तावेज़ रखें। प्रत्येक पृष्ठ पर आपके जीपीएस स्थान, निर्देशांक और टाइमस्टैम्प का वॉटरमार्क लगाया जाएगा।',
    startScanning: 'स्कैनिंग शुरू करें',
    locWatermark: 'स्थान वॉटरमार्क',
    locWatermarkDesc: 'हर पेज पर जीपीएस निर्देशांक, स्थान का नाम और सटीकता।',
    timestamp: 'टाइमस्टैम्प',
    timestampDesc: 'प्रत्येक स्कैन किए गए पृष्ठ पर अंकित सटीक कैप्चर समय।',
    downloadPdf: 'पीडीएफ के रूप में डाउनलोड करें',
    downloadPdfDesc: 'सीधे आपके डिवाइस पर सहेजी गई एक वास्तविक पीडीएफ फाइल उत्पन्न करता है।',
    alignDoc: 'दस्तावेज़ के किनारों को संरेखित करें',
    pageCaptured: 'पेज कैप्चर किया गया',
    pagesCaptured: 'पेज कैप्चर किए गए',
    reviewAndSave: 'समीक्षा करें और सहेजें',
    reviewPages: 'पृष्ठों की समीक्षा करें',
    addPage: 'पेज जोड़ें',
    savePdf: 'पीडीएफ सहेजें',
    pdfSavedTitle: 'पीडीएफ सहेजा गया! ✅',
    pdfSavedBody: 'वॉटरमार्क के साथ पीडीएफ आपके डिवाइस पर सहेज लिया गया है।',
    sharePdf: 'पीडीएफ साझा करें',
    scanMore: 'और स्कैन करें',
    discardPagesTitle: 'पृष्ठों को हटा दें?',
    discardPagesBody: 'आपके पास स्कैन किए गए पृष्ठ हैं। उन्हें हटा दें?',
    discard: 'हटा दें',

    // Geo Camera Screen
    cameraAccessNeeded: 'कैमरा एक्सेस की आवश्यकता है',
    cameraAccessDesc: 'लाइव पूर्वावलोकन तुरंत शुरू करने के लिए हमें कैमरा एक्सेस की आवश्यकता है।',
    startCamera: 'कैमरा शुरू करें',
    allowLocationWatermark: 'स्थान वॉटरमार्क बंद है',
    allowLocationWatermarkDesc: 'अक्षांश, देशांतर, सटीकता और कैप्चर समय अंकित करने के लिए स्थान की अनुमति दें।',
    reviewYourShot: 'अपने शॉट की समीक्षा करें',
    useThisShot: 'इस शॉट का उपयोग करें',
    retake: 'पुनः प्रयास करें',
    crop: 'क्रॉप',
    applyCrop: 'क्रॉप लागू करें',

    // Profile Screen
    profile: 'प्रोफ़ाइल',
    manageAccount: 'अपने खाते और प्राथमिकताओं को प्रबंधित करें।',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    yourActivity: 'आपकी गतिविधि',
    documents: 'दस्तावेज़',
    locations: 'स्थान',
    storage: 'स्टोरेज',
    settings: 'सेटिंग्स',
    cloudSync: 'क्लाउड सिंक',
    privacySecurity: 'गोपनीयता और सुरक्षा',
    appearance: 'थीम',
    helpSupport: 'सहायता और समर्थन',
    changeLanguage: 'भाषा',
    signOut: 'लॉग आउट',
    signingOut: 'लॉग आउट हो रहा है…',
  },
  es: {
    // Common
    cancel: 'Cancelar',
    save: 'Guardar',
    done: 'Hecho',
    ready: 'Listo',
    synced: 'Sincronizado',
    close: 'Cerrar',
    back: 'Atrás',
    loading: 'Cargando…',

    // Tab bar
    homeTab: 'Inicio',
    pdfScanTab: 'Escanear PDF',
    geoScanTab: 'Escaneo Geo',
    profileTab: 'Perfil',

    // Home screen
    goodMorning: 'Buen día',
    goodAfternoon: 'Buenas tardes',
    goodEvening: 'Buenas noches',
    whatToCapture: '¿Qué te gustaría capturar hoy?',
    scanPdf: 'Escanear PDF',
    scanPdfDesc: 'Páginas → PDF con marca de agua',
    geoScan: 'Escaneo Geo',
    geoScanDesc: 'Foto + coordenadas GPS',
    totalScans: 'Escaneos totales',
    cloudSynced: 'Sincronizado',
    thisWeek: 'Esta semana',
    smartCrop: 'Recorte Inteligente',
    smartCropDesc: 'Recorta tus fotos geo-etiquetadas con controles precisos y proporciones',
    recentActivity: 'Actividad reciente',
    viewAll: 'Ver todo',

    // PDF Scanner Screen
    pdfScannerTitle: 'Escáner PDF',
    pdfScannerSubtitle: 'Captura, marca de agua y guarda documentos con datos GPS.',
    scanADoc: 'Escanear un documento',
    scanADocDesc: 'Coloque su documento sobre una superficie plana con buena iluminación. Cada página tendrá una marca de agua con su ubicación GPS, coordenadas y marca de tiempo.',
    startScanning: 'Comenzar escaneo',
    locWatermark: 'Marca de agua de ubicación',
    locWatermarkDesc: 'Coordenadas GPS, nombre del lugar y precisión en cada página.',
    timestamp: 'Marca de tiempo',
    timestampDesc: 'Hora exacta de captura estampada en cada página escaneada.',
    downloadPdf: 'Descargar como PDF',
    downloadPdfDesc: 'Genera un archivo PDF real guardado directamente en su dispositivo.',
    alignDoc: 'Alinear los bordes del documento',
    pageCaptured: 'página capturada',
    pagesCaptured: 'páginas capturadas',
    reviewAndSave: 'Revisar y Guardar',
    reviewPages: 'Revisar Páginas',
    addPage: 'Añadir Página',
    savePdf: 'Guardar PDF',
    pdfSavedTitle: '¡PDF Guardado! ✅',
    pdfSavedBody: 'El PDF con marca de agua ha sido guardado en tu dispositivo.',
    sharePdf: 'Compartir PDF',
    scanMore: 'Escanear más',
    discardPagesTitle: '¿Descartar páginas?',
    discardPagesBody: 'Tienes páginas escaneadas. ¿Descartarlas?',
    discard: 'Descartar',

    // Geo Camera Screen
    cameraAccessNeeded: 'Acceso a la cámara necesario',
    cameraAccessDesc: 'Necesitamos acceso a la cámara para iniciar la vista previa de inmediato.',
    startCamera: 'Iniciar cámara',
    allowLocationWatermark: 'Marca de agua desactivada',
    allowLocationWatermarkDesc: 'Permite la ubicación para estampar latitud, longitud, precisión y hora.',
    reviewYourShot: 'Revisa tu captura',
    useThisShot: 'Usar captura',
    retake: 'Repetir',
    crop: 'Recortar',
    applyCrop: 'Aplicar Recorte',

    // Profile Screen
    profile: 'Perfil',
    manageAccount: 'Gestiona tu cuenta y preferencias.',
    editProfile: 'Editar perfil',
    yourActivity: 'Tu actividad',
    documents: 'Documentos',
    locations: 'Ubicaciones',
    storage: 'Almacenamiento',
    settings: 'Configuración',
    cloudSync: 'Sincronización en la nube',
    privacySecurity: 'Privacidad y seguridad',
    appearance: 'Apariencia',
    helpSupport: 'Soporte y ayuda',
    changeLanguage: 'Idioma',
    signOut: 'Cerrar sesión',
    signingOut: 'Cerrando sesión…',
  },
};
